export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAIL = 'USER_INFO_FAIL';


export const USER_REPO_SUCCESS = 'USER_REPO_SUCCESS';
export const USER_REPO_FAIL = 'USER_REPO_FAIL';